### ISSUE TITLE
AutoRemoveColumns _should_column_fetch example incorrect

### ISSUE THREAD

**Issue by abraxxa** [frioux/DBIx-Class-Helpers#106]
Using https://metacpan.org/pod/DBIx::Class::Helper::ResultSet::AutoRemoveColumns#_should_column_fetch results in `Can't locate object method "column_info" via package "My::Schema::ResultSet::Foo"` because the `->result_source` is missing.

**Comment by abraxxa** [comment]
And the code is logically also incorrect.
This doesn't always return 1:

```
sub _should_column_fetch {
    my ( $self, $column ) = @_;

    my $info = $self->result_source->column_info($column);

    return exists $info->{remove_column}
      ? $info->{remove_column}
      : 0;
}
```

**Comment by abraxxa** [comment]
One more thing: the sub name `_should_column_fetch` suggests that it has to return a false value to prevent a column from being fetched while the opposite is true (pun intended).

**Comment by frioux** [comment]
please provide a pull request and a test.

**Comment by abraxxa** [comment]
I've created the PR, Github seems to not link it because of GH#106 instead of just #106.
No test because it's just a doc patch.

Renaming the sub would introduce a breaking change so I haven't done that. Maybe adding documentation to clearly describe the expected return values can be done as a workaround.

**Comment by frioux** [comment]
Awesome, thanks

**Comment by abraxxa** [comment]
Sorry for the late reply, it seems I've left the brower tab open and didn't hit 'Comment':

One more thing: the sub name `_should_column_fetch` suggests that it has to return a false value to prevent a column from being fetched while the opposite is true (pun intended).
