### ISSUE TITLE
Feature: Best Practices check

### ISSUE THREAD

**Issue by mcsnolte** [frioux/DBIx-Class-Helpers#31]
Similar to how PBP are checked with https://metacpan.org/pod/Perl::Critic it would be very useful for doing something similar for DBIC Schemas.  Here are some examples:

* Relationship names should not match column names
* NULL-able belongs_to relationships should use LEFT join type

**Comment by frioux** [comment]
We can use this to implement these: https://metacpan.org/pod/release/FREW/DBIx-Class-Helpers-2.026000/lib/DBIx/Class/Helper/Schema/Verifier.pm

**Comment by mcsnolte** [comment]
Looks perfect!  Cool, I hope I can work on this soon

**Comment by frioux** [comment]
If not I'll get around to it eventually

-- 
sent from a rotary phone, pardon my brevity

**Comment by frioux** [comment]
Got the relname != colname one released

**Comment by frioux** [comment]
I'm gonna call this done.  Create issues for each one that you think is worth doing.
