### ISSUE TITLE
not_null shortcut

### ISSUE THREAD

**Issue by moltar** [frioux/DBIx-Class-Helpers#44]
What do you think about having a `not_null` shortcut?

Example from my own use:

```perl
=head2 not_null($column)

Ensure that given C<$column> is not null.

=cut

sub not_null {
    my ($self, $column) = @_;

    return $self->search_rs({ $self->me($column) => { '!=' => undef } });
}
```

**Comment by frioux** [comment]
Seems legit to me; should we make a `null`, `like`, and `not_like` too while we're at it?

@wesQ3 thoughts?

**Comment by wesQ3** [comment]
Sounds good. We're probably overdue for some search condition shortcuts rather than just smoothing out search attributes.

**Comment by frioux** [comment]
@moltar if you send a PR with docs and tests (you're halfway there!) I'll look at merging it.  Otherwise this'll go on the stack and I'll release it before too long.

**Comment by moltar** [comment]
Should each go into a separate package or do we bundle them into some namespace, like SearchShortcuts?

**Comment by frioux** [comment]
Good question.  I think that each one should be a separate package, but they should all be used in SearchShortcuts.  That way if the user wants everything they just use SearchShortcuts but if they want to not use a few they can do that.

**Comment by moltar** [comment]
Another question. Should be prefix them with "`me.`" via `->me` method or should we leave this exercise up to the user?

**Comment by frioux** [comment]
Do what I did in datemethods!  If the user does `.foo`, prefix; if the user does just `foo`, leave it alone.

**Comment by moltar** [comment]
So I was trying to figure out what the best name space would be. My proposition is:

`DBIx::Class::Helper::ResultSet::Shortcut::Search::$NAME`

And then just load them up in `DBIx::Class::Helper::ResultSet::Shortcut` with all the other ones?

Or do we want them to load separately?

**Comment by frioux** [comment]
Yeah that namespace sounds perfect, just load it into Shortcut

-- 
sent from a rotary phone, pardon my brevity

**Comment by moltar** [comment]
Please review

https://github.com/moltar/DBIx-Class-Helpers/tree/feature/search-shortcuts

**Comment by moltar** [comment]
Added in #47

**Comment by frioux** [comment]
This looks good @moltar.  Could you remove the [headers](https://github.com/frioux/DBIx-Class-Helpers/pull/47/files#diff-82fc53120cfa7b3ab6db6acdc2cfe8a9R8) from the methods that already have POD documentation?  The ones for private methods are fine.  Thanks!

**Comment by moltar** [comment]
Done.

**Comment by frioux** [comment]
released!
