### ISSUE TITLE
[PATCH] add abstract to POD

### ISSUE THREAD

**Issue by gregoa** [frioux/DBIx-Class-Helpers#49]
In Debian we are currently applying the following patch to
DBIx-Class-Helpers.
We thought you might be interested in it too.

    Description: add abstract to POD
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2015-06-28
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libdbix-class-helpers-perl.git/plain/debian/patches/abstract.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by frioux** [comment]
Thanks, included, should be in the next release, probably next week.
