### ISSUE TITLE
Create DBIx::Class::Helper::ResultSet::Bare

### ISSUE THREAD

**Issue by frioux** [frioux/DBIx-Class-Helpers#53]
```perl
$rs->bare
```

Basically, sometimes you need to access the full ResultSet from a searched RS.
Maybe come up with a better name?

**Comment by mcsnolte** [comment]
Nice, and I do like the name.  `reset()` is already taken.  Something like `clean()` or `pristine()` might be vague.  `unsearched()` is dumb.  A search for synonyms didn't help:  `bald()`, `naked()`, `peeled()`, `stripped()`, etc.

**Comment by frioux** [comment]
Mmmmm, Copyright violations

 <img src="http://nakedjuice.com/resources/imgs/logo.png"></img>
