### ISSUE TITLE
Create a ::ResultClass::Tee

### ISSUE THREAD

**Issue by frioux** [frioux/DBIx-Class-Helpers#56]
@Relequestual needed something like this and I think it would be both generally useful and a great example on how to make custom ResultClasses

```
@frew | package MyApp::Schema::ResultClass::Tee; sub new { return [ ::HRI->new(@_), ::Foo->new(@_) ] }
@frew | the hard part is that you'll want to store the name of ::Foo (say, MyApp::Schema::Result::User) in an attr, so you'll have to make
      | an instantiation method other than new
```

**Comment by Relequestual** [comment]
cc @simonbrent

**Comment by frioux** [comment]
Done and released with the name DBIx::Class::Helper::ResultClass::Tee

**Comment by Relequestual** [comment]
Awesome thankyou! =]
Out of interest, how did you arrive at the name?

**Comment by frioux** [comment]
Look up the tee command. It let's you write to multiple outputs (usually
stdout and a file) from a single input

-- 
sent from a rotary phone, pardon my brevity
