### ISSUE TITLE
ToJSON misconvert integer to string

### ISSUE THREAD

**Issue by fangyuan** [frioux/DBIx-Class-Helpers#59]
When convert Row data to json using `ToJSON`,  the column with integer type will be converted to string. Of course, I could make the value to integer via `$a + 0`. Is there anyway auto do that, make sure the integer column to integer.
Thanks.

**Comment by frioux** [comment]
Check out DBIx::Class::Helper::Row::NumifyGet

-- 
sent from a rotary phone, pardon my brevity

**Comment by fangyuan** [comment]
Thanks, this module is really what I want.
I read the source code and run test, then I update the column attrs and include this module, but still failed to export as number using `TO_JSON` or `get_column`. Then I use the method `is_numeric` in `NumifyGet.t` to assert the value return by `get_column`, the result is `0`. The module seems does not work. Any suggestion? Thanks

**Comment by frioux** [comment]
Use both of the modules and you should get what you are after; they are specifically made to be used together.

**Comment by frioux** [comment]
Closing this.  Feel free to comment or reach out on IRC if you need more help.
