### ISSUE TITLE
A tad cleaner ProxyResultMethod

### ISSUE THREAD

**Issue by ribasushi** [frioux/DBIx-Class-Helpers#66]
While reading https://github.com/frioux/DBIx-Class-Helpers/issues/39 I was looking at [this](https://github.com/frioux/DBIx-Class-Helpers/blob/master/lib/DBIx/Class/Helper/Row/ProxyResultSetMethod.pm#L34) and it occurred to me it can be improved a bit: only resort to internals grubbing in order to "touch" the slot into existence. Afterwards use `set_column` as usual to reinvoke the dirty/cache-invalidate/etc machinery.

**Comment by frioux** [comment]
Fixed via 13a70d62fa4
