### ISSUE TITLE
[PATCH] spelling fixes

### ISSUE THREAD

**Issue by gregoa** [frioux/DBIx-Class-Helpers#71]
In Debian we are currently applying the following patch to
DBIx-Class-Helpers.
We thought you might be interested in it too.

    Description: spelling fixes
    Origin: vendor
    Author: gregor herrmann <gregoa@debian.org>
    Last-Update: 2016-07-24
    

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libdbix-class-helpers-perl.git/plain/debian/patches/spelling.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by frioux** [comment]
Applied!  Will release soon.
