### ISSUE TITLE
[PATCH] Fix a strictness error in a deprecated module

### ISSUE THREAD

**Issue by gregoa** [frioux/DBIx-Class-Helpers#72]
In Debian we are currently applying the following patch to
DBIx-Class-Helpers.
We thought you might be interested in it too.

    From 3502789f7aaabf4490fb060e238d69258704ee26 Mon Sep 17 00:00:00 2001
    From: Niko Tyni <ntyni@debian.org>
    Date: Fri, 19 Sep 2014 12:54:58 +0300
    Subject: [PATCH] Fix a strictness error in a deprecated module
    
    The deprecation messages refer to $VERSION, which isn't
    declared despite 'use strict'. This causes a compile
    time error.

The patch is tracked in our Git repository at
https://anonscm.debian.org/cgit/pkg-perl/packages/libdbix-class-helpers-perl.git/plain/debian/patches/0001-Fix-a-strictness-error-in-a-deprecated-module.patch

Thanks for considering,
  gregor herrmann,
  Debian Perl Group

**Comment by frioux** [comment]
Patch applied!  Thanks!
